import { useCallback, useEffect, useState } from "react";
import { Building2, Check, Edit3, LoaderCircle, Lock, RefreshCw, Save, X } from "lucide-react";
import { authFetch } from "../api/authFetch";
import { OpenModuleSetting, useOpenModules } from "../open-modules";
interface Props{currentTenantId:number;isSuperAdmin:boolean}
export default function OpenModuleManagementTab({currentTenantId,isSuperAdmin}:Props){
 const reload=useOpenModules(s=>s.load),[tenants,setTenants]=useState<any[]>([]),[selected,setSelected]=useState(currentTenantId),[tenantName,setTenantName]=useState(""),[modules,setModules]=useState<OpenModuleSetting[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState<string|null>(null),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async(id:number)=>{setLoading(true);setError("");try{const r=await authFetch(`/api/module-settings?tenant_id=${id}`),d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"加载失败");setModules(d.data.modules);setTenantName(d.data.tenant.name)}catch(e){setError(e instanceof Error?e.message:"加载失败")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load(selected)},[selected,load]);useEffect(()=>{if(isSuperAdmin)void authFetch("/api/admin/tenants").then(r=>r.json()).then(d=>{if(d.success)setTenants(d.data||[])}).catch(()=>{})},[isSuperAdmin]);
 const save=async(payload:any,key:string,success:string)=>{setSaving(key);setError("");setMessage("");try{const r=await authFetch("/api/module-settings",{method:"PUT",body:JSON.stringify({tenant_id:selected,...payload})}),d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"保存失败");setModules(d.data.modules);setMessage(success);if(selected===currentTenantId)await reload()}catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setSaving(null)}};
 const toggle=(item:OpenModuleSetting)=>void save({updates:{[item.key]:!item.enabled}},item.key,`${item.label}已${item.enabled?"关闭":"开启"}`);
 const saveName=(item:OpenModuleSetting)=>void save({labels:{[item.key]:draft}},item.key,`${item.defaultLabel}已改名为${draft.trim()}`).then(()=>setEditing(null));
 return <div className="max-w-5xl space-y-4"><div><h2 className="text-sm font-semibold">租户模块管理</h2><p className="text-xs text-text-muted mt-1">开关会同步控制侧栏与路由；显示名称按租户保存，不修改模块代码标识。</p></div>
 {isSuperAdmin?<label className="block max-w-sm text-xs">管理租户<select value={selected} onChange={e=>setSelected(Number(e.target.value))} className="mt-2 w-full px-3 py-2 border border-border rounded bg-bg-card">{tenants.length?tenants.map(t=><option key={t.id} value={t.id}>{t.name} · {t.status}</option>):<option value={currentTenantId}>{tenantName||"当前租户"}</option>}</select></label>:<div className="flex gap-2 text-xs text-text-muted"><Building2 size={14}/>正在管理：<b className="text-text">{tenantName}</b></div>}
 {message&&<div className="text-xs text-success bg-success/10 px-3 py-2 rounded flex gap-2"><Check size={14}/>{message}</div>}{error&&<div className="text-xs text-danger bg-danger/10 px-3 py-2 rounded flex justify-between">{error}<button onClick={()=>void load(selected)}><RefreshCw size={13}/></button></div>}
 {loading?<div className="h-40 grid place-items-center text-xs text-text-muted"><span className="flex gap-2"><LoaderCircle size={16} className="animate-spin"/>加载模块配置…</span></div>:<div className="grid md:grid-cols-2 gap-3">{modules.map(item=><div key={item.key} className="p-4 bg-bg-card border border-border rounded-lg">
  <div className="flex items-start gap-3"><div className="flex-1 min-w-0">{editing===item.key?<div className="flex gap-2"><input autoFocus value={draft} onChange={e=>setDraft(e.target.value)} maxLength={20} className="min-w-0 flex-1 px-2 py-1 border border-primary rounded bg-bg text-sm"/><button onClick={()=>saveName(item)} disabled={saving!==null} className="p-1.5 bg-primary text-white rounded"><Save size={14}/></button><button onClick={()=>setEditing(null)} className="p-1.5 border border-border rounded"><X size={14}/></button></div>:<div className="flex items-center gap-2"><p className="text-sm font-medium">{item.label}</p><button onClick={()=>{setEditing(item.key);setDraft(item.label)}} className="text-text-muted hover:text-primary" title="编辑显示名称"><Edit3 size={13}/></button><span className={`text-[10px] px-2 py-0.5 rounded ${item.enabled?"bg-success/10 text-success":"bg-bg text-text-muted"}`}>{item.enabled?"已开启":"已关闭"}</span></div>}<p className="text-[11px] text-text-muted mt-2">{item.description}</p><code className="text-[10px] text-text-muted">@openxyos/{item.key}</code></div>
  {item.locked?<span className="w-11 h-6 rounded-full bg-primary/20 text-primary grid place-items-center" title="基础模块始终保留"><Lock size={13}/></span>:<button role="switch" aria-checked={item.enabled} disabled={saving!==null} onClick={()=>toggle(item)} className={`relative w-11 h-6 rounded-full ${item.enabled?"bg-primary":"bg-gray-300"}`}><span className={`absolute top-.5 left-.5 w-5 h-5 bg-white rounded-full shadow transition-transform ${item.enabled?"translate-x-5":""}`}>{saving===item.key&&<LoaderCircle size={12} className="animate-spin m-1 text-primary"/>}</span></button>}
  </div></div>)}</div>}
 <div className="text-[11px] text-text-muted border-t border-border pt-3">工作台与系统设置是恢复和管理入口，始终保留；其名称仍可编辑。模块开关不会提升用户权限。</div></div>;
}
